# user_not_found_exception.py

class UserNotFoundException(Exception):
    """Exception raised when a user is not found."""
    pass
